base_url = "https://divijesh.com"
title = "Home"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
favicon = "https://divijesh.com/favicon.ico"
#release = "https://api.github.com/repos/getzola/zola/releases/latest"
logo = "https://divijesh.com/hms.svg"
